# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Southern East Cree spellchecker"
crj = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Southern East Cree, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
crj = "TRANSLATE: A spellchecker for Southern East Cree, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.crj"

[windows]
system_product_code = "{47B802EE-5FB6-4E1E-AAE8-2CBB20A0CCEC}_is1"
legacy_product_codes = [
    { value = "DAEE3C9F-BFD4-4CE7-885B-155AD05D8367", kind = "nsis" },
    { value = "5C762710-6594-4753-9140-42A57F54E8D8", kind = "nsis" }
]

[package.speller]
name = "Southern East Cree"
version = "0.1.1"

[package.grammar]
name = "Southern East Cree"
version = "0.1.0"

[package.tts-textproc]
name = "Southern East Cree"
version = "0.1.0"

[package.hyphenator]
name = "Southern East Cree"
version = "0.1.0"
