template = "https://github.com/giellalt/template-lang-und"
rev_id = 280
template_sha = "6beee360d8349c39749ac477719ead241493924c"

[replacements]
__GLOTTOLOG_ID__ = "sout2978"
__REPO__ = "lang-crj"
__UND2C__ = "crj"
__UNDEFINED__ = "Southern East Cree"
__UND__ = "crj"
