template = "https://github.com/giellalt/template-lang-und"
rev_id = 267
template_sha = "eecc8ba78a1297394fa54b425d94002ee6604eb1"

[replacements]
__GLOTTOLOG_ID__ = "sout2978"
__REPO__ = "lang-crj"
__UND2C__ = "crj"
__UNDEFINED__ = "Southern East Cree"
__UND__ = "crj"
