template = "https://github.com/giellalt/template-lang-und"
rev_id = 265
template_sha = "55c74340aa57ef2b38d3f84b2a9790e969781f56"

[replacements]
__GLOTTOLOG_ID__ = "sout2978"
__REPO__ = "lang-crj"
__UND2C__ = "crj"
__UNDEFINED__ = "Southern East Cree"
__UND__ = "crj"
